[package]
name = "vinyl"
version = "0.1.0"
authors = [
	"Tyler J. Russell <nytelife@protonmail.com>",
	"doge <doge@helper.wtf>",
	"Stitch07 (github.com/stitch07)",
	"Pyrotechniac <owenbellish@gmail.com>"
]
edition = "2018"
license = "MIT"

[dependencies]
thiserror = "1.0.25"
