[package]
name = "vinyl"
version = "0.1.0"
authors = [
	"Tyler J. Russell <t@k-cs.co>",
	"doge <doge@helper.wtf>",
	"Stitch (github.com/soumil-07)",
	"Pyrotechniac <owenbellish@gmail.com>"
]
edition = "2018"
license = "MIT"

[dependencies]
bytes = "1.1.0"
thiserror = "1.0.25"
